### ISSUE TITLE
Add support for all Expansion card support for Pro3's

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#124] opened 2020-04-27 19:05 UTC

**Comment by TrevorPayne** [comment] 2020-05-20 19:53
I think I may be able to do this utilizing the methodology I did with inifinet EX client devices.  I'll look into this.

That being said, I think I may have to modify the relay and GPIO control classes to push back registration into PostActivate as was done in the comm classes.

**Comment by andrew-welker** [comment] 2020-07-02 15:53
Duplicate of 125

**Closed** 2020-07-02 15:53 UTC
Labels: enhancement
